name: Install ODBC drivers for mssql
description: Install ODBC drivers for mssql
branding:
  icon: 'database'
  color: 'green'
inputs:
  ODBC_VERSION:
    description: 'ODBC version to install (18 or 17 validated)'
    default: "18"
  DISTRO:
    description: 'Distribution (from DOCS_URL)'
    default: Ubuntu
  DOCS_URL:
    description: 'URL to the docs page to scrape instructions from'
    default: "https://raw.githubusercontent.com/MicrosoftDocs/sql-docs/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md"
  REMOVE_EXITS:
    default: 'true'
    description: 'Remove exit statements from the script (they break the workflow)'

runs:
  using: composite
  steps:
    - run: |
        pip install requests
        python extract_instruction_from_readme.py | bash
      env:
        DISTRO: ${{ inputs.DISTRO }}
        DOCS_URL: ${{ inputs.DOCS_URL }}
        REMOVE_EXITS: ${{ inputs.REMOVE_EXITS }}
        ODBC_VERSION: ${{ inputs.ODBC_VERSION }}
      shell: bash
